In [50]:
myfile = open('/content/ai_updates.txt')
mytext = myfile.read()
myfile.close()
print(mytext)

Artificial intelligence (AI) capabilities have rapidly evolved, transforming industries and society by automating tasks, enhancing decision-making, and enabling new forms of personalization and efficiency. AI systems now perform a wide range of functions, from basic automation to complex data analysis and adaptive learning, and are increasingly integrated into business, healthcare, logistics, and everyday life.ibm+2​
Core AI Capabilities
AI capabilities can be grouped into several key areas:
* Automation: AI excels at automating repetitive, rule-based tasks, such as data entry, scheduling, and customer support, freeing human workers for more strategic activities.lumenalta​

* Predictive and Prescriptive Analytics: AI analyzes vast datasets to forecast trends, optimize inventory, and recommend actions, helping organizations make data-driven decisions.lumenalta​

* Personalization: AI-powered engines tailor customer experiences, improving engagement and increasing revenue through target

In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])

In [52]:
word_index = mytokenizer.word_index
word_index

{'and': 1,
 'ai': 2,
 'to': 3,
 'intelligence': 4,
 'https': 5,
 'artificial': 6,
 'capabilities': 7,
 'com': 8,
 'of': 9,
 'data': 10,
 'a': 11,
 'lumenalta\u200b': 12,
 'www': 13,
 'systems': 14,
 'learning': 15,
 'business': 16,
 'is': 17,
 'the': 18,
 'by': 19,
 'personalization': 20,
 'automation': 21,
 'ibm': 22,
 'as': 23,
 'human': 24,
 'organizations': 25,
 'make': 26,
 'decisions': 27,
 'in': 28,
 'insights': 29,
 'brookings\u200b': 30,
 'future': 31,
 'rapidly': 32,
 'transforming': 33,
 'industries': 34,
 'society': 35,
 'automating': 36,
 'tasks': 37,
 'decision': 38,
 'making': 39,
 'enabling': 40,
 'new': 41,
 'efficiency': 42,
 'perform': 43,
 'from': 44,
 'complex': 45,
 'are': 46,
 'into': 47,
 'logistics': 48,
 'can': 49,
 'customer': 50,
 'for': 51,
 'more': 52,
 'analytics': 53,
 'improving': 54,
 'increasing': 55,
 'while': 56,
 'task': 57,
 'operations': 58,
 'indatalabs\u200b': 59,
 'learn': 60,
 'time': 61,
 'they': 62,
 'changing': 63,
 'drive': 64,
 'mckinsey

In [53]:
total_words = len(word_index) + 1
print("Vocabulary size:" , total_words)

Vocabulary size: 288


In [54]:
lines = mytext.split('\n')
print(lines[0])
print()
print(lines[1])
print()
print(lines[2])

Artificial intelligence (AI) capabilities have rapidly evolved, transforming industries and society by automating tasks, enhancing decision-making, and enabling new forms of personalization and efficiency. AI systems now perform a wide range of functions, from basic automation to complex data analysis and adaptive learning, and are increasingly integrated into business, healthcare, logistics, and everyday life.ibm+2​

Core AI Capabilities

AI capabilities can be grouped into several key areas:


* For training language models - generate n-gram sequences
* for each line in the text, we create sequences that incrementally add one word at a time, which will train model to predict the next word given a sequence.

In [55]:
my_input_sequences = []

for line in lines:
  token_list = mytokenizer.texts_to_sequences([line])[0]
  #print(token_list)
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[ :i+1]
    #print(n_gram_sequence)
    my_input_sequences.append(n_gram_sequence)

In [56]:
print(my_input_sequences)

[[72, 4], [72, 4, 2], [72, 4, 2, 7], [72, 4, 2, 7, 73], [72, 4, 2, 7, 73, 32], [72, 4, 2, 7, 73, 32, 74], [72, 4, 2, 7, 73, 32, 74, 33], [72, 4, 2, 7, 73, 32, 74, 33, 34], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39, 1], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39, 1, 40], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39, 1, 40, 41], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39, 1, 40, 41, 76], [72, 4, 2, 7, 73, 32, 74, 33, 34, 1, 35, 19, 36, 37, 75, 38, 39, 1, 40, 41, 76, 9], [72, 4, 2, 7, 73, 32, 74, 33

In [57]:
print(my_input_sequences[0])
print(my_input_sequences[1])
print(my_input_sequences[2])

[72, 4]
[72, 4, 2]
[72, 4, 2, 7]


**Padding**

In [58]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_seq_len = max([len(seq) for seq in my_input_sequences])
my_input_sequences = pad_sequences(my_input_sequences , maxlen=max_seq_len , padding='pre')
print(my_input_sequences)

[[ 0  0  0 ...  0 72  4]
 [ 0  0  0 ... 72  4  2]
 [ 0  0  0 ...  4  2  7]
 ...
 [ 0  0  0 ...  6  4  6]
 [ 0  0  0 ...  4  6  4]
 [ 0  0  0 ...  6  4 31]]


In [59]:
import numpy as np

X = my_input_sequences[:,:-1]
y = my_input_sequences[:,-1]

In [60]:
X

array([[ 0,  0,  0, ...,  0,  0, 72],
       [ 0,  0,  0, ...,  0, 72,  4],
       [ 0,  0,  0, ..., 72,  4,  2],
       ...,
       [ 0,  0,  0, ...,  8,  6,  4],
       [ 0,  0,  0, ...,  6,  4,  6],
       [ 0,  0,  0, ...,  4,  6,  4]], dtype=int32)

In [61]:
X.shape

(454, 69)

In [62]:
y = y.reshape(-1,1)
y.shape

(454, 1)

In [63]:
y

array([[  4],
       [  2],
       [  7],
       [ 73],
       [ 32],
       [ 74],
       [ 33],
       [ 34],
       [  1],
       [ 35],
       [ 19],
       [ 36],
       [ 37],
       [ 75],
       [ 38],
       [ 39],
       [  1],
       [ 40],
       [ 41],
       [ 76],
       [  9],
       [ 20],
       [  1],
       [ 42],
       [  2],
       [ 14],
       [ 77],
       [ 43],
       [ 11],
       [ 78],
       [ 79],
       [  9],
       [ 80],
       [ 44],
       [ 81],
       [ 21],
       [  3],
       [ 45],
       [ 10],
       [ 82],
       [  1],
       [ 83],
       [ 15],
       [  1],
       [ 46],
       [ 84],
       [ 85],
       [ 47],
       [ 16],
       [ 86],
       [ 48],
       [  1],
       [ 87],
       [ 88],
       [ 22],
       [ 89],
       [  2],
       [  7],
       [  7],
       [ 49],
       [ 91],
       [ 92],
       [ 47],
       [ 93],
       [ 94],
       [ 95],
       [  2],
       [ 96],
       [ 97],
       [ 36],
       [ 98],
      

In [64]:
from tensorflow.keras.utils import to_categorical

yt = to_categorical(y , num_classes=total_words)
yt

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [65]:
print("Feature shape:" , X.shape)
print("Feature shape:" , yt.shape)

Feature shape: (454, 69)
Feature shape: (454, 288)


In [69]:
from tensorflow.keras import models, layers

model = models.Sequential()
model.add(layers.Embedding(total_words , output_dim=50 , input_length=max_seq_len-1))
model.add(layers.Flatten()) # Add a Flatten layer here
model.add(layers.Dense(16 , activation='relu'))
model.add(layers.Dense(288 , activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [70]:
model.compile(loss = 'categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])

In [71]:
model.fit(X , yt , epochs = 100)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0041 - loss: 5.6606
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0123 - loss: 5.6214
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0295 - loss: 5.5176
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0504 - loss: 5.4689
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0582 - loss: 5.3355
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0679 - loss: 5.2407
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0615 - loss: 5.2394
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0627 - loss: 5.1914
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0613 - loss: 5.0666
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0833 - loss: 4.9618
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0772 - loss: 4.8779
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy:

In [74]:
X.shape

(454, 69)

In [82]:
for val,id in mytokenizer.word_index.items():
  if id == 2:
    print(val)

ai


In [98]:
input_text = "learning"

predict_next_words = 25

for k in range(predict_next_words):
  token_list = mytokenizer.texts_to_sequences([input_text])[0]
  token_list = pad_sequences([token_list] , maxlen=max_seq_len-1 , padding='pre')
  #print(token_list)
  predicted = np.argmax(model.predict(token_list))
  #print(predicted)
  for val,id in mytokenizer.word_index.items():
    if id == predicted:
      output_word = val
      print(output_word)

  input_text = input_text + " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
ai
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
capabilities
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
can
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
grouped
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
into
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
several
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
key
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
areas
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
rapidly
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
as
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
recommendations
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
operations
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
competitive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
world
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
business
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
operational
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
perform
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
a
1/1 ━━━━━━━━